esphome:
  name: garage-doors
  friendly_name: Garage Doors

substitutions:
  disp_name: garage

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret garage-door-api-key

ota:
  password: !secret garage-door-ota-pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Doors Fallback Hotspot"
    password: !secret garage-door-ap-pass

captive_portal:

switch:
  - platform: gpio
    #name: ${disp_name} Relay1
    pin:
      number: GPIO22
      inverted: True
    id: relay1
    restore_mode: ALWAYS_OFF 

  - platform: gpio
    #name: ${disp_name} Relay2
    pin:
      number: GPIO23
      inverted: True
    id: relay2
    restore_mode: ALWAYS_OFF 
  - platform: restart
    name: ${disp_name} Restart

binary_sensor:
  - platform: gpio
    name: ${disp_name} Reed1
    pin: 
      number: GPIO18
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    id: reed_switch1
    internal: true
  - platform: gpio
    name: ${disp_name} Reed2
    pin: 
      number: GPIO19
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    id: reed_switch2
    internal: true

    
cover:
  - platform: template
    device_class: garage
    name: ${disp_name} Door 1
    id: template_cover1
    lambda: |-
      if (id(reed_switch1).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: relay1
      - delay: 0.5s
      - switch.turn_off: relay1
    close_action:
      - switch.turn_on: relay1
      - delay: 0.5s
      - switch.turn_off: relay1      
    stop_action:
      - switch.turn_on: relay1
      - delay: 0.5s
      - switch.turn_off: relay1      
  - platform: template
    device_class: garage
    name: ${disp_name} Door 2
    id: template_cover2
    lambda: |-
      if (id(reed_switch2).state) {
        return COVER_OPEN;
      } else {
        return COVER_CLOSED;
      }
    open_action:
      - switch.turn_on: relay2
      - delay: 0.5s
      - switch.turn_off: relay2
    close_action:
      - switch.turn_on: relay2
      - delay: 0.5s
      - switch.turn_off: relay2
    stop_action:
      - switch.turn_on: relay2
      - delay: 0.5s
      - switch.turn_off: relay2
