substitutions:
  device_name: master-bed-fan
  friendly_name: Master Bedroom Fan
  
esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0
  
# Enable Home Assistant API
api:
  encryption:
#    key: !secret mj-fc-01-master-bed-api-key
    key: !secret api-key

ota:
#  password: !secret mj-fc-01-master-bed-ota-pass
  password: !secret ota-pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret ap-pass
#    password: !secret mj-fc-01-master-bed-ap-pass

captive_portal:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:

fan:
  - platform: "tuya"
    name: Master Bedroom Fan Speed
    restore_mode: ALWAYS_OFF
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4
    
