esphome:
  name: master-bed-fan

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0
  
# Enable Home Assistant API
api:
  encryption:
    key: !secret master-bed-fan-api-key

ota:
  password: !secret master-bed-fan-ota-pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Master-Bed-Fan Fallback Hotspot"
    password: !secret master-bed-fan-ap-pass

captive_portal:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:

fan:
  - platform: "tuya"
    name: Master Bedroom Fan Speed
    restore_mode: ALWAYS_OFF
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4
    
